<!DOCTYPE html>
<html lang="" xml:lang="">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>8 Raster GIS operations in R with terra | A Minimal Introduction to GIS (in R)</title>
  <meta name="description" content="This is a minimal introduction to GIS and handling spatial data in R compiled for the Biological Sciences BSc(Honours) class at the University of Cape Town." />
  <meta name="generator" content="bookdown 0.46 and GitBook 2.6.7" />

  <meta property="og:title" content="8 Raster GIS operations in R with terra | A Minimal Introduction to GIS (in R)" />
  <meta property="og:type" content="book" />
  
  <meta property="og:description" content="This is a minimal introduction to GIS and handling spatial data in R compiled for the Biological Sciences BSc(Honours) class at the University of Cape Town." />
  <meta name="github-repo" content="jslingsby/spatial-r" />

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="8 Raster GIS operations in R with terra | A Minimal Introduction to GIS (in R)" />
  
  <meta name="twitter:description" content="This is a minimal introduction to GIS and handling spatial data in R compiled for the Biological Sciences BSc(Honours) class at the University of Cape Town." />
  

<meta name="author" content="Jasper Slingsby" />


<meta name="date" content="2026-02-26" />

  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  
<link rel="prev" href="rdemo.html"/>
<link rel="next" href="references.html"/>
<script src="libs/jquery-3.6.0/jquery-3.6.0.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/fuse.js@6.4.6/dist/fuse.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-clipboard.css" rel="stylesheet" />








<link href="libs/anchor-sections-1.1.0/anchor-sections.css" rel="stylesheet" />
<link href="libs/anchor-sections-1.1.0/anchor-sections-hash.css" rel="stylesheet" />
<script src="libs/anchor-sections-1.1.0/anchor-sections.js"></script>


<style type="text/css">
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { color: #008000; } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { color: #008000; font-weight: bold; } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>

<style type="text/css">
  
  div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
</style>

<link rel="stylesheet" href="style.css" type="text/css" />
</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li><a href="./">A Minimal Intro to GIS in R</a></li>

<li class="divider"></li>
<li class="chapter" data-level="1" data-path="index.html"><a href="index.html"><i class="fa fa-check"></i><b>1</b> Overview</a>
<ul>
<li class="chapter" data-level="1.1" data-path="index.html"><a href="index.html#general"><i class="fa fa-check"></i><b>1.1</b> General</a></li>
<li class="chapter" data-level="1.2" data-path="index.html"><a href="index.html#using"><i class="fa fa-check"></i><b>1.2</b> Using this resource</a></li>
<li class="chapter" data-level="1.3" data-path="index.html"><a href="index.html#module-and-project-details"><i class="fa fa-check"></i><b>1.3</b> Module and Project details</a></li>
</ul></li>
<li class="chapter" data-level="2" data-path="intro.html"><a href="intro.html"><i class="fa fa-check"></i><b>2</b> Why care about GIS?</a></li>
<li class="chapter" data-level="3" data-path="gis-basics.html"><a href="gis-basics.html"><i class="fa fa-check"></i><b>3</b> GIS basics</a>
<ul>
<li class="chapter" data-level="3.1" data-path="gis-basics.html"><a href="gis-basics.html#what-is-gis"><i class="fa fa-check"></i><b>3.1</b> What is GIS?</a>
<ul>
<li class="chapter" data-level="3.1.1" data-path="gis-basics.html"><a href="gis-basics.html#an-example-workflow"><i class="fa fa-check"></i><b>3.1.1</b> An example workflow</a></li>
</ul></li>
<li class="chapter" data-level="3.2" data-path="gis-basics.html"><a href="gis-basics.html#how-do-we-do-gis"><i class="fa fa-check"></i><b>3.2</b> How do we do GIS?</a></li>
<li class="chapter" data-level="3.3" data-path="gis-basics.html"><a href="gis-basics.html#ucthelp"><i class="fa fa-check"></i><b>3.3</b> How to get help?</a></li>
</ul></li>
<li class="chapter" data-level="4" data-path="gis-data-models-and-file-formats.html"><a href="gis-data-models-and-file-formats.html"><i class="fa fa-check"></i><b>4</b> GIS data models and file formats</a>
<ul>
<li class="chapter" data-level="4.1" data-path="gis-data-models-and-file-formats.html"><a href="gis-data-models-and-file-formats.html#data-models"><i class="fa fa-check"></i><b>4.1</b> Data models</a>
<ul>
<li class="chapter" data-level="4.1.1" data-path="gis-data-models-and-file-formats.html"><a href="gis-data-models-and-file-formats.html#vector-data"><i class="fa fa-check"></i><b>4.1.1</b> Vector data</a></li>
<li class="chapter" data-level="4.1.2" data-path="gis-data-models-and-file-formats.html"><a href="gis-data-models-and-file-formats.html#raster-data"><i class="fa fa-check"></i><b>4.1.2</b> Raster data</a></li>
</ul></li>
<li class="chapter" data-level="4.2" data-path="gis-data-models-and-file-formats.html"><a href="gis-data-models-and-file-formats.html#attribute-data"><i class="fa fa-check"></i><b>4.2</b> Attribute data</a></li>
<li class="chapter" data-level="4.3" data-path="gis-data-models-and-file-formats.html"><a href="gis-data-models-and-file-formats.html#file-formats"><i class="fa fa-check"></i><b>4.3</b> File formats</a></li>
</ul></li>
<li class="chapter" data-level="5" data-path="some-important-concepts-and-pitfalls.html"><a href="some-important-concepts-and-pitfalls.html"><i class="fa fa-check"></i><b>5</b> Some important concepts and pitfalls</a>
<ul>
<li class="chapter" data-level="5.1" data-path="some-important-concepts-and-pitfalls.html"><a href="some-important-concepts-and-pitfalls.html#scale"><i class="fa fa-check"></i><b>5.1</b> Scale</a></li>
<li class="chapter" data-level="5.2" data-path="some-important-concepts-and-pitfalls.html"><a href="some-important-concepts-and-pitfalls.html#coordinate-reference-systems-crs"><i class="fa fa-check"></i><b>5.2</b> Coordinate Reference Systems (CRS)</a>
<ul>
<li class="chapter" data-level="5.2.1" data-path="some-important-concepts-and-pitfalls.html"><a href="some-important-concepts-and-pitfalls.html#geographic-or-unprojected-coordinate-systems"><i class="fa fa-check"></i><b>5.2.1</b> Geographic (or “unprojected”) Coordinate Systems</a></li>
<li class="chapter" data-level="5.2.2" data-path="some-important-concepts-and-pitfalls.html"><a href="some-important-concepts-and-pitfalls.html#projection"><i class="fa fa-check"></i><b>5.2.2</b> Projected Coordinate Systems</a></li>
<li class="chapter" data-level="5.2.3" data-path="some-important-concepts-and-pitfalls.html"><a href="some-important-concepts-and-pitfalls.html#projection-codes"><i class="fa fa-check"></i><b>5.2.3</b> Projection codes</a></li>
<li class="chapter" data-level="5.2.4" data-path="some-important-concepts-and-pitfalls.html"><a href="some-important-concepts-and-pitfalls.html#on-the-fly-vs-manual-projection"><i class="fa fa-check"></i><b>5.2.4</b> “On the fly” vs manual projection</a></li>
<li class="chapter" data-level="5.2.5" data-path="some-important-concepts-and-pitfalls.html"><a href="some-important-concepts-and-pitfalls.html#the-golden-rules"><i class="fa fa-check"></i><b>5.2.5</b> The golden rules…</a></li>
</ul></li>
<li class="chapter" data-level="5.3" data-path="some-important-concepts-and-pitfalls.html"><a href="some-important-concepts-and-pitfalls.html#counts-rates-and-the-modifiable-areal-unit-problem-maup"><i class="fa fa-check"></i><b>5.3</b> Counts, rates and the Modifiable Areal Unit Problem (MAUP)</a></li>
</ul></li>
<li class="chapter" data-level="6" data-path="r-as-a-gis.html"><a href="r-as-a-gis.html"><i class="fa fa-check"></i><b>6</b> R as a GIS</a>
<ul>
<li class="chapter" data-level="6.1" data-path="r-as-a-gis.html"><a href="r-as-a-gis.html#overview-1"><i class="fa fa-check"></i><b>6.1</b> Overview</a></li>
<li class="chapter" data-level="6.2" data-path="r-as-a-gis.html"><a href="r-as-a-gis.html#some-key-r-packages"><i class="fa fa-check"></i><b>6.2</b> Some key R packages</a>
<ul>
<li class="chapter" data-level="6.2.1" data-path="r-as-a-gis.html"><a href="r-as-a-gis.html#for-vector-data"><i class="fa fa-check"></i><b>6.2.1</b> For vector data</a></li>
<li class="chapter" data-level="6.2.2" data-path="r-as-a-gis.html"><a href="r-as-a-gis.html#for-raster-data"><i class="fa fa-check"></i><b>6.2.2</b> For raster data</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="7" data-path="rdemo.html"><a href="rdemo.html"><i class="fa fa-check"></i><b>7</b> Vector GIS operations in R</a>
<ul>
<li class="chapter" data-level="7.1" data-path="rdemo.html"><a href="rdemo.html#casestudy"><i class="fa fa-check"></i><b>7.1</b> Case study and demo datasets</a></li>
<li class="chapter" data-level="7.2" data-path="rdemo.html"><a href="rdemo.html#reading-and-writing"><i class="fa fa-check"></i><b>7.2</b> Reading and writing</a></li>
<li class="chapter" data-level="7.3" data-path="rdemo.html"><a href="rdemo.html#basic-plotting"><i class="fa fa-check"></i><b>7.3</b> Basic plotting</a></li>
<li class="chapter" data-level="7.4" data-path="rdemo.html"><a href="rdemo.html#cropping"><i class="fa fa-check"></i><b>7.4</b> Cropping</a></li>
<li class="chapter" data-level="7.5" data-path="rdemo.html"><a href="rdemo.html#select-and-subset-by-attribute"><i class="fa fa-check"></i><b>7.5</b> Select and subset by attribute</a></li>
<li class="chapter" data-level="7.6" data-path="rdemo.html"><a href="rdemo.html#combine-classes-and-dissolve-by-attribute"><i class="fa fa-check"></i><b>7.6</b> Combine classes and dissolve by attribute</a></li>
<li class="chapter" data-level="7.7" data-path="rdemo.html"><a href="rdemo.html#getinat"><i class="fa fa-check"></i><b>7.7</b> Calling iNaturalist locality (point) data from R</a></li>
<li class="chapter" data-level="7.8" data-path="rdemo.html"><a href="rdemo.html#converting-a-dataframe-into-a-spatial-object"><i class="fa fa-check"></i><b>7.8</b> Converting a dataframe into a spatial object</a></li>
<li class="chapter" data-level="7.9" data-path="rdemo.html"><a href="rdemo.html#adding-basemaps-to-plots"><i class="fa fa-check"></i><b>7.9</b> Adding basemaps to plots</a></li>
<li class="chapter" data-level="7.10" data-path="rdemo.html"><a href="rdemo.html#interactive-maps-with-leaflet-and-mapview"><i class="fa fa-check"></i><b>7.10</b> Interactive maps with <em>leaflet</em> and <em>mapview</em></a></li>
<li class="chapter" data-level="7.11" data-path="rdemo.html"><a href="rdemo.html#projections"><i class="fa fa-check"></i><b>7.11</b> Reprojecting</a></li>
<li class="chapter" data-level="7.12" data-path="rdemo.html"><a href="rdemo.html#intersecting-points-and-polygons"><i class="fa fa-check"></i><b>7.12</b> Intersecting points and polygons</a></li>
<li class="chapter" data-level="7.13" data-path="rdemo.html"><a href="rdemo.html#colour-or-label-points"><i class="fa fa-check"></i><b>7.13</b> Colour or label points</a></li>
<li class="chapter" data-level="7.14" data-path="rdemo.html"><a href="rdemo.html#buffering"><i class="fa fa-check"></i><b>7.14</b> Buffering</a></li>
<li class="chapter" data-level="7.15" data-path="rdemo.html"><a href="rdemo.html#within-distance-and-intersect"><i class="fa fa-check"></i><b>7.15</b> Within distance and intersect</a></li>
</ul></li>
<li class="chapter" data-level="8" data-path="terra.html"><a href="terra.html"><i class="fa fa-check"></i><b>8</b> Raster GIS operations in R with <em>terra</em></a>
<ul>
<li class="chapter" data-level="8.1" data-path="terra.html"><a href="terra.html#reading-in-data"><i class="fa fa-check"></i><b>8.1</b> Reading in data</a></li>
<li class="chapter" data-level="8.2" data-path="terra.html"><a href="terra.html#defining-crs-and-projecting"><i class="fa fa-check"></i><b>8.2</b> Defining CRS and projecting</a></li>
<li class="chapter" data-level="8.3" data-path="terra.html"><a href="terra.html#cropping-1"><i class="fa fa-check"></i><b>8.3</b> Cropping</a></li>
<li class="chapter" data-level="8.4" data-path="terra.html"><a href="terra.html#aggregating-resampling"><i class="fa fa-check"></i><b>8.4</b> Aggregating / Resampling</a></li>
<li class="chapter" data-level="8.5" data-path="terra.html"><a href="terra.html#basic-plotting-1"><i class="fa fa-check"></i><b>8.5</b> Basic plotting</a></li>
<li class="chapter" data-level="8.6" data-path="terra.html"><a href="terra.html#disaggregating"><i class="fa fa-check"></i><b>8.6</b> Disaggregating</a></li>
<li class="chapter" data-level="8.7" data-path="terra.html"><a href="terra.html#raster-maths"><i class="fa fa-check"></i><b>8.7</b> Raster maths!</a></li>
<li class="chapter" data-level="8.8" data-path="terra.html"><a href="terra.html#focal-and-terrain-calculations"><i class="fa fa-check"></i><b>8.8</b> Focal and terrain calculations</a></li>
<li class="chapter" data-level="8.9" data-path="terra.html"><a href="terra.html#raster-stacks"><i class="fa fa-check"></i><b>8.9</b> Raster stacks</a></li>
<li class="chapter" data-level="8.10" data-path="terra.html"><a href="terra.html#extracting-raster-to-vector"><i class="fa fa-check"></i><b>8.10</b> Extracting raster to vector</a></li>
<li class="chapter" data-level="8.11" data-path="terra.html"><a href="terra.html#rasterizing"><i class="fa fa-check"></i><b>8.11</b> Rasterizing</a></li>
<li class="chapter" data-level="8.12" data-path="terra.html"><a href="terra.html#crosstabulating-rasters"><i class="fa fa-check"></i><b>8.12</b> Crosstabulating rasters</a></li>
<li class="chapter" data-level="8.13" data-path="terra.html"><a href="terra.html#visualizing-multiple-datasets-on-one-map"><i class="fa fa-check"></i><b>8.13</b> Visualizing multiple datasets on one map</a></li>
<li class="chapter" data-level="8.14" data-path="terra.html"><a href="terra.html#cloud-optimized-geotiffs-cogs"><i class="fa fa-check"></i><b>8.14</b> Cloud Optimized GeoTiffs (COGs)!!!</a></li>
<li class="chapter" data-level="8.15" data-path="terra.html"><a href="terra.html#obtaining-satellite-data-from-apis"><i class="fa fa-check"></i><b>8.15</b> Obtaining satellite data from APIs</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="references.html"><a href="references.html"><i class="fa fa-check"></i>References</a></li>
<li class="divider"></li>
<li><a href="https://github.com/rstudio/bookdown" target="blank">Published with bookdown</a></li>

</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">A Minimal Introduction to GIS (in R)</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="terra" class="section level1 hasAnchor" number="8">
<h1><span class="header-section-number">8</span> Raster GIS operations in R with <em>terra</em><a href="terra.html#terra" class="anchor-section" aria-label="Anchor link to header"></a></h1>
<div id="reading-in-data" class="section level2 hasAnchor" number="8.1">
<h2><span class="header-section-number">8.1</span> Reading in data<a href="terra.html#reading-in-data" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>Ok, now to look at handling rasters. As with <em>sf</em>, the <em>terra</em> package has one function -<code>rast()</code>- that can read in just about any raster file format, which it assigns it’s own class <code>SpatRaster</code>. Let’s get started and read in the digital elevation model (DEM) for the City of Cape Town.</p>
<div class="sourceCode" id="cb1"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb1-1"><a href="terra.html#cb1-1" tabindex="-1"></a><span class="fu">library</span>(terra)</span></code></pre></div>
<pre><code>## terra 1.8.93</code></pre>
<div class="sourceCode" id="cb3"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb3-1"><a href="terra.html#cb3-1" tabindex="-1"></a>dem <span class="ot">&lt;-</span> <span class="fu">rast</span>(<span class="st">&quot;data/cape_peninsula/CoCT_10m.tif&quot;</span>)</span>
<span id="cb3-2"><a href="terra.html#cb3-2" tabindex="-1"></a></span>
<span id="cb3-3"><a href="terra.html#cb3-3" tabindex="-1"></a><span class="fu">class</span>(dem)</span></code></pre></div>
<pre><code>## [1] &quot;SpatRaster&quot;
## attr(,&quot;package&quot;)
## [1] &quot;terra&quot;</code></pre>
<div class="sourceCode" id="cb5"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb5-1"><a href="terra.html#cb5-1" tabindex="-1"></a>dem <span class="co">#Typing the name of a &quot;SpatRaster&quot; class data object gives you the details</span></span></code></pre></div>
<pre><code>## class       : SpatRaster 
## size        : 9902, 6518, 1  (nrow, ncol, nlyr)
## resolution  : 10, 10  (x, y)
## extent      : -64180, 1000, -3804020, -3705000  (xmin, xmax, ymin, ymax)
## coord. ref. : GCS_WGS_1984 
## source      : CoCT_10m.tif 
## name        : 10m_BA 
## min value   :    -35 
## max value   :   1590</code></pre>
<p>The <code>coord. ref.</code> field shows <code>GCS_WGS_1984</code>, which is Geographic Coordinates, but perhaps there is a projected CRS too? The extent appears to be in metres, with the eastings being a mix of positive and negative numbers, from which we can deduce that the coordinate reference system may be Transverse Mercator centred on Lo19, as for the other datasets we obtained from the City of Cape Town. Best to make sure! If you just want to know the CRS from a SpatRaster, you just call <code>crs()</code> like so:</p>
<div class="sourceCode" id="cb7"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb7-1"><a href="terra.html#cb7-1" tabindex="-1"></a><span class="fu">crs</span>(dem)</span></code></pre></div>
<pre><code>## [1] &quot;PROJCRS[\&quot;GCS_WGS_1984\&quot;,\n    BASEGEOGCRS[\&quot;WGS 84\&quot;,\n        DATUM[\&quot;World Geodetic System 1984\&quot;,\n            ELLIPSOID[\&quot;WGS 84\&quot;,6378137,298.25722356049,\n                LENGTHUNIT[\&quot;metre\&quot;,1]]],\n        PRIMEM[\&quot;Greenwich\&quot;,0,\n            ANGLEUNIT[\&quot;degree\&quot;,0.0174532925199433]],\n        ID[\&quot;EPSG\&quot;,4326]],\n    CONVERSION[\&quot;Transverse Mercator\&quot;,\n        METHOD[\&quot;Transverse Mercator\&quot;,\n            ID[\&quot;EPSG\&quot;,9807]],\n        PARAMETER[\&quot;Latitude of natural origin\&quot;,0,\n            ANGLEUNIT[\&quot;degree\&quot;,0.0174532925199433],\n            ID[\&quot;EPSG\&quot;,8801]],\n        PARAMETER[\&quot;Longitude of natural origin\&quot;,19,\n            ANGLEUNIT[\&quot;degree\&quot;,0.0174532925199433],\n            ID[\&quot;EPSG\&quot;,8802]],\n        PARAMETER[\&quot;Scale factor at natural origin\&quot;,1,\n            SCALEUNIT[\&quot;unity\&quot;,1],\n            ID[\&quot;EPSG\&quot;,8805]],\n        PARAMETER[\&quot;False easting\&quot;,0,\n            LENGTHUNIT[\&quot;metre\&quot;,1],\n            ID[\&quot;EPSG\&quot;,8806]],\n        PARAMETER[\&quot;False northing\&quot;,0,\n            LENGTHUNIT[\&quot;metre\&quot;,1],\n            ID[\&quot;EPSG\&quot;,8807]]],\n    CS[Cartesian,2],\n        AXIS[\&quot;easting\&quot;,east,\n            ORDER[1],\n            LENGTHUNIT[\&quot;metre\&quot;,1,\n                ID[\&quot;EPSG\&quot;,9001]]],\n        AXIS[\&quot;northing\&quot;,north,\n            ORDER[2],\n            LENGTHUNIT[\&quot;metre\&quot;,1,\n                ID[\&quot;EPSG\&quot;,9001]]]]&quot;</code></pre>
<p>Messy, but somewhere in there it says “Longitude of natural origin 19” and “Transverse Mercator”…</p>
<p><br></p>
</div>
<div id="defining-crs-and-projecting" class="section level2 hasAnchor" number="8.2">
<h2><span class="header-section-number">8.2</span> Defining CRS and projecting<a href="terra.html#defining-crs-and-projecting" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>Similar to <code>st_crs()</code>, you can define a projection using the syntax:</p>
<p><code>crs(your_raster) &lt;- "your_crs"</code>, where the new CRS can be in WKT, and EPSG code, or a PROJ string.</p>
<p>For reprojecting, you use the function <code>project()</code>. We’ll look at it later in the section on Cloud Optimized GeoTiffs.</p>
<p><br></p>
</div>
<div id="cropping-1" class="section level2 hasAnchor" number="8.3">
<h2><span class="header-section-number">8.3</span> Cropping<a href="terra.html#cropping-1" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>Ok, before we try to anything with this dataset, let’s think about how big it is… One of the outputs of calling <code>dem</code> was the row reading <code>dimensions : 9902, 6518, 1  (nrow, ncol, nlyr)</code>. Given that we are talking about 10m pixels, this information tells us that the extent of the region is roughly 100km by 65km and that there are ~65 million pixels! No wonder the original file was ~130MB (I reduced the one I shared with you slightly).</p>
<p>While R can handle this, it does become slow when dealing with very large files. There are many ways to improve the efficiency of handling big rasters in R (see <a href="https://www.ecologi.st/post/big-spatial-data/">this slightly dated post for details</a> if you’re interested), but for the purposes of this tutorial we’re going to take the easy option and just crop it to a smaller extent, like so:</p>
<div class="sourceCode" id="cb9"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb9-1"><a href="terra.html#cb9-1" tabindex="-1"></a>dem <span class="ot">&lt;-</span> <span class="fu">crop</span>(dem, <span class="fu">ext</span>(<span class="fu">c</span>(<span class="sc">-</span><span class="fl">66642.18</span>, <span class="sc">-</span><span class="fl">44412.18</span>, <span class="sc">-</span><span class="fl">3809853.29</span>, <span class="sc">-</span><span class="fl">3750723.29</span>)))</span></code></pre></div>
<p>Note that the <code>crop()</code> function requires us to pass it an object of class <code>SpatExtent</code>. Just like <code>st_crop()</code> from <em>sf</em>, <code>crop()</code> can derive the extent from another data object.</p>
<p>One silly difference, is that if you pass it the coordinates of the extent manually (as above), you first need to pass it to the <code>ext()</code> function, and they need to follow the order <em>xmin, xmax, ymin, ymax</em> (as opposed to <em>xmin, ymin, xmax, ymax</em> as you do for <code>st_crop()</code>). Keep your eye out for these little differences, because they will trip you up…</p>
<p>Ok, so how big is our dataset now?</p>
<div class="sourceCode" id="cb10"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb10-1"><a href="terra.html#cb10-1" tabindex="-1"></a>dem</span></code></pre></div>
<pre><code>## class       : SpatRaster 
## size        : 5330, 1977, 1  (nrow, ncol, nlyr)
## resolution  : 10, 10  (x, y)
## extent      : -64180, -44410, -3804020, -3750720  (xmin, xmax, ymin, ymax)
## coord. ref. : GCS_WGS_1984 
## source(s)   : memory
## varname     : CoCT_10m 
## name        : 10m_BA 
## min value   :    -15 
## max value   :   1084</code></pre>
<p>…still &gt;10 million pixels…</p>
<p><br></p>
</div>
<div id="aggregating-resampling" class="section level2 hasAnchor" number="8.4">
<h2><span class="header-section-number">8.4</span> Aggregating / Resampling<a href="terra.html#aggregating-resampling" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>Do we need 10m data? If your analysis doesn’t need such fine resolution data, you can resample the raster to a larger pixel size, like 30m. The <code>aggregate()</code> function does this very efficiently, like so:</p>
<div class="sourceCode" id="cb12"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb12-1"><a href="terra.html#cb12-1" tabindex="-1"></a>dem30 <span class="ot">&lt;-</span> <span class="fu">aggregate</span>(dem, <span class="at">fact =</span> <span class="dv">3</span>, <span class="at">fun =</span> mean)</span></code></pre></div>
<pre><code>## |---------|---------|---------|---------|=========================================                                          </code></pre>
<p>Here I’ve told it to aggregate by a factor of 3 (i.e. bin 9 neighbouring pixels (3x3) into one) and to assign the bigger pixel the mean of the 9 original pixels. This obviously results in some data loss, but that can be acceptable, depending on the purpose of your analysis. Note that you can pass just about any function to <code>fun =</code>, like <code>min()</code>, <code>max()</code> or even your own function.</p>
<div class="sourceCode" id="cb14"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb14-1"><a href="terra.html#cb14-1" tabindex="-1"></a>dem30</span></code></pre></div>
<pre><code>## class       : SpatRaster 
## size        : 1777, 659, 1  (nrow, ncol, nlyr)
## resolution  : 30, 30  (x, y)
## extent      : -64180, -44410, -3804030, -3750720  (xmin, xmax, ymin, ymax)
## coord. ref. : GCS_WGS_1984 
## source(s)   : memory
## name        :   10m_BA 
## min value   :  -15.000 
## max value   : 1083.556</code></pre>
<p>Ok, so we’ve reduced the size of the raster by a factor of 9 and only have a little over 1 million pixels to deal with. Much more reasonable! Now let’s have a look at what we’re dealing with.</p>
<p><br></p>
</div>
<div id="basic-plotting-1" class="section level2 hasAnchor" number="8.5">
<h2><span class="header-section-number">8.5</span> Basic plotting<a href="terra.html#basic-plotting-1" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>Now that we’ve reduced the size of the dataset, we can try the base plotting function:</p>
<div class="sourceCode" id="cb16"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb16-1"><a href="terra.html#cb16-1" tabindex="-1"></a><span class="fu">plot</span>(dem30)</span></code></pre></div>
<p><img src="spatial-r_files/figure-html/unnamed-chunk-7-1.png" alt="" width="672" /></p>
<p>Or with the <em>Tidyverse</em>…</p>
<p>Note that <code>ggplot()</code> doesn’t accept rasters, so we need to give it a dataframe with <em>x</em> and <em>y</em> columns for the coordinates, and a column containing the values to plot. This is easily done by coercing the raster into a dataframe, like so:</p>
<div class="sourceCode" id="cb17"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb17-1"><a href="terra.html#cb17-1" tabindex="-1"></a><span class="co">#call tidyverse libraries and plot</span></span>
<span id="cb17-2"><a href="terra.html#cb17-2" tabindex="-1"></a><span class="fu">library</span>(tidyverse)</span></code></pre></div>
<pre><code>## ── Attaching core tidyverse packages ──────────────────────── tidyverse 2.0.0 ──
## ✔ dplyr     1.2.0     ✔ readr     2.2.0
## ✔ forcats   1.0.1     ✔ stringr   1.6.0
## ✔ ggplot2   4.0.2     ✔ tibble    3.3.1
## ✔ lubridate 1.9.5     ✔ tidyr     1.3.2
## ✔ purrr     1.2.1     
## ── Conflicts ────────────────────────────────────────── tidyverse_conflicts() ──
## ✖ tidyr::extract() masks terra::extract()
## ✖ dplyr::filter()  masks stats::filter()
## ✖ dplyr::lag()     masks stats::lag()
## ℹ Use the conflicted package (&lt;http://conflicted.r-lib.org/&gt;) to force all conflicts to become errors</code></pre>
<div class="sourceCode" id="cb19"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb19-1"><a href="terra.html#cb19-1" tabindex="-1"></a>dem30 <span class="sc">%&gt;%</span> <span class="fu">as.data.frame</span>(<span class="at">xy =</span> <span class="cn">TRUE</span>) <span class="sc">%&gt;%</span></span>
<span id="cb19-2"><a href="terra.html#cb19-2" tabindex="-1"></a>  <span class="fu">ggplot</span>() <span class="sc">+</span></span>
<span id="cb19-3"><a href="terra.html#cb19-3" tabindex="-1"></a>  <span class="fu">geom_raster</span>(<span class="fu">aes</span>(<span class="at">x =</span> x, <span class="at">y =</span> y, <span class="at">fill =</span> <span class="st">`</span><span class="at">10m_BA</span><span class="st">`</span>))</span></code></pre></div>
<p><img src="spatial-r_files/figure-html/unnamed-chunk-8-1.png" alt="" width="336" /></p>
<div class="sourceCode" id="cb20"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb20-1"><a href="terra.html#cb20-1" tabindex="-1"></a><span class="co"># Note that I had to know that the column name for the elevation data is &quot;10m_BA&quot;... and that you need to use ` ` around a variable name when feeding it to a function if it starts with a digit.</span></span></code></pre></div>
<p>Ok, how different does our 30m raster look to the 10m version?</p>
<div class="sourceCode" id="cb21"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb21-1"><a href="terra.html#cb21-1" tabindex="-1"></a>dem <span class="sc">%&gt;%</span></span>
<span id="cb21-2"><a href="terra.html#cb21-2" tabindex="-1"></a>  <span class="fu">as.data.frame</span>(<span class="at">xy =</span> <span class="cn">TRUE</span>) <span class="sc">%&gt;%</span></span>
<span id="cb21-3"><a href="terra.html#cb21-3" tabindex="-1"></a>  <span class="fu">ggplot</span>() <span class="sc">+</span></span>
<span id="cb21-4"><a href="terra.html#cb21-4" tabindex="-1"></a>  <span class="fu">geom_raster</span>(<span class="fu">aes</span>(<span class="at">x =</span> x, <span class="at">y =</span> y, <span class="at">fill =</span> <span class="st">`</span><span class="at">10m_BA</span><span class="st">`</span>))</span></code></pre></div>
<p><img src="spatial-r_files/figure-html/unnamed-chunk-9-1.png" alt="" width="336" /></p>
<p>Not noticeably different at this scale!</p>
<p><br></p>
</div>
<div id="disaggregating" class="section level2 hasAnchor" number="8.6">
<h2><span class="header-section-number">8.6</span> Disaggregating<a href="terra.html#disaggregating" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>One way to explore the degree of data loss is to <code>disagg()</code> our 30m DEM back to 10m and then compare it to the original.</p>
<div class="sourceCode" id="cb22"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb22-1"><a href="terra.html#cb22-1" tabindex="-1"></a>dem10 <span class="ot">&lt;-</span> <span class="fu">disagg</span>(dem30, <span class="at">fact =</span> <span class="dv">3</span>, <span class="at">method =</span> <span class="st">&quot;bilinear&quot;</span>)</span></code></pre></div>
<p>Note that I’ve tried to use <em>bilinear interpolation</em> to give it a fair chance of getting nearer the original values. You can google this on your own, but it essentially smooths the data by averaging across neighbouring pixels.</p>
<p>Now, how can I compare my two 10m rasters?</p>
<p><br></p>
</div>
<div id="raster-maths" class="section level2 hasAnchor" number="8.7">
<h2><span class="header-section-number">8.7</span> Raster maths!<a href="terra.html#raster-maths" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>The <em>raster</em> and <em>terra</em> packages make this easy, because you can do maths with rasters, treating them as variables in an equation. This means we can explore the data loss by calculating the difference between the original and disaggregated DEMS.</p>
<p>Note that when aggregating you often lose some of the cells along the edges, and that you can’t do raster maths on rasters with different extents… We can fix this by cropping the larger raster with the smaller first.</p>
<div class="sourceCode" id="cb23"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb23-1"><a href="terra.html#cb23-1" tabindex="-1"></a>dem10 <span class="ot">&lt;-</span> <span class="fu">crop</span>(dem10, dem)</span>
<span id="cb23-2"><a href="terra.html#cb23-2" tabindex="-1"></a></span>
<span id="cb23-3"><a href="terra.html#cb23-3" tabindex="-1"></a>diff <span class="ot">&lt;-</span> dem <span class="sc">-</span> dem10 <span class="co">#maths with rasters!</span></span></code></pre></div>
<p>And plot the result!</p>
<div class="sourceCode" id="cb24"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb24-1"><a href="terra.html#cb24-1" tabindex="-1"></a>diff <span class="sc">%&gt;%</span></span>
<span id="cb24-2"><a href="terra.html#cb24-2" tabindex="-1"></a>  <span class="fu">as.data.frame</span>(<span class="at">xy =</span> <span class="cn">TRUE</span>) <span class="sc">%&gt;%</span></span>
<span id="cb24-3"><a href="terra.html#cb24-3" tabindex="-1"></a>  <span class="fu">ggplot</span>() <span class="sc">+</span></span>
<span id="cb24-4"><a href="terra.html#cb24-4" tabindex="-1"></a>  <span class="fu">geom_raster</span>(<span class="fu">aes</span>(<span class="at">x =</span> x, <span class="at">y =</span> y, <span class="at">fill =</span> <span class="st">`</span><span class="at">10m_BA</span><span class="st">`</span>)) </span></code></pre></div>
<p><img src="spatial-r_files/figure-html/unnamed-chunk-12-1.png" alt="" width="336" /></p>
<p>If you look <em>really</em> closely, you’ll see the outline of the cliffs of Table Mountain, where you’d expect the data loss to be worst. The colour ramp tells us that the worst distortion was up to 100m, or about 10% of the elevation range in this dataset, but don’t be fooled by the extremes! Let’s have a look at all the values as a histogram.</p>
<div class="sourceCode" id="cb25"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb25-1"><a href="terra.html#cb25-1" tabindex="-1"></a>diff <span class="sc">%&gt;%</span></span>
<span id="cb25-2"><a href="terra.html#cb25-2" tabindex="-1"></a>  <span class="fu">as.data.frame</span>(<span class="at">xy =</span> <span class="cn">TRUE</span>) <span class="sc">%&gt;%</span></span>
<span id="cb25-3"><a href="terra.html#cb25-3" tabindex="-1"></a>  <span class="fu">ggplot</span>() <span class="sc">+</span></span>
<span id="cb25-4"><a href="terra.html#cb25-4" tabindex="-1"></a>  <span class="fu">geom_histogram</span>(<span class="fu">aes</span>(<span class="st">`</span><span class="at">10m_BA</span><span class="st">`</span>))</span></code></pre></div>
<pre><code>## `stat_bin()` using `bins = 30`. Pick better value `binwidth`.</code></pre>
<p><img src="spatial-r_files/figure-html/unnamed-chunk-13-1.png" alt="" width="672" /></p>
<p>Looks like most values are within 10 or so metres of their original values, so the data loss really wasn’t that bad!</p>
<p><br></p>
</div>
<div id="focal-and-terrain-calculations" class="section level2 hasAnchor" number="8.8">
<h2><span class="header-section-number">8.8</span> Focal and terrain calculations<a href="terra.html#focal-and-terrain-calculations" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>In addition to maths with multiple rasters, you can do all kinds of calculations within a raster using <code>focal()</code>. This essentially applies a moving window, calculating values for a neighbourhood of cells as it goes, using whatever function you supply (mean, max, your own, etc).</p>
<p>The function <code>terrain()</code> is a special case of <code>focal()</code>, optimized for calculating <em>slope, aspect, topographic position index (TPI), topographic roughness index (TRI), roughness, or flow direction</em>.</p>
<p>Here I’ll calculate the slope and aspect so that we can pass them to the function <code>shade()</code> to make a pretty hillshade layer.</p>
<div class="sourceCode" id="cb27"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb27-1"><a href="terra.html#cb27-1" tabindex="-1"></a>aspect <span class="ot">&lt;-</span> <span class="fu">terrain</span>(dem30, <span class="st">&quot;aspect&quot;</span>, <span class="at">unit =</span> <span class="st">&quot;radians&quot;</span>)</span>
<span id="cb27-2"><a href="terra.html#cb27-2" tabindex="-1"></a></span>
<span id="cb27-3"><a href="terra.html#cb27-3" tabindex="-1"></a>slope <span class="ot">&lt;-</span> <span class="fu">terrain</span>(dem30, <span class="st">&quot;slope&quot;</span>, <span class="at">unit =</span> <span class="st">&quot;radians&quot;</span>)</span>
<span id="cb27-4"><a href="terra.html#cb27-4" tabindex="-1"></a></span>
<span id="cb27-5"><a href="terra.html#cb27-5" tabindex="-1"></a>hillshade <span class="ot">&lt;-</span> <span class="fu">shade</span>(slope, aspect)</span>
<span id="cb27-6"><a href="terra.html#cb27-6" tabindex="-1"></a></span>
<span id="cb27-7"><a href="terra.html#cb27-7" tabindex="-1"></a><span class="fu">plot</span>(hillshade)</span></code></pre></div>
<p><img src="spatial-r_files/figure-html/unnamed-chunk-14-1.png" alt="" width="672" /></p>
<p>Probably prettier with <em>Tidyverse</em>:</p>
<div class="sourceCode" id="cb28"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb28-1"><a href="terra.html#cb28-1" tabindex="-1"></a>hillshade <span class="sc">%&gt;%</span></span>
<span id="cb28-2"><a href="terra.html#cb28-2" tabindex="-1"></a>  <span class="fu">as.data.frame</span>(<span class="at">xy =</span> <span class="cn">TRUE</span>) <span class="sc">%&gt;%</span></span>
<span id="cb28-3"><a href="terra.html#cb28-3" tabindex="-1"></a>  <span class="fu">ggplot</span>() <span class="sc">+</span></span>
<span id="cb28-4"><a href="terra.html#cb28-4" tabindex="-1"></a>  <span class="fu">geom_raster</span>(<span class="fu">aes</span>(<span class="at">x =</span> x, <span class="at">y =</span> y, <span class="at">fill =</span> hillshade)) <span class="sc">+</span> <span class="co">#note that the hillshade column name in this case is &quot;hillshade&quot;</span></span>
<span id="cb28-5"><a href="terra.html#cb28-5" tabindex="-1"></a>  <span class="fu">scale_fill_gradient</span>(<span class="at">low =</span> <span class="st">&quot;grey10&quot;</span>, <span class="at">high =</span> <span class="st">&quot;grey90&quot;</span>)</span></code></pre></div>
<p><img src="spatial-r_files/figure-html/unnamed-chunk-15-1.png" alt="" width="336" /></p>
<p>Nice ne?</p>
<p><br></p>
</div>
<div id="raster-stacks" class="section level2 hasAnchor" number="8.9">
<h2><span class="header-section-number">8.9</span> Raster stacks<a href="terra.html#raster-stacks" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>Another nice thing about rasters is that if you have multiple rasters “on the same grid” (i.e. with the same pixel size, extent and CRS) then you can stack them and work with them as a single object. <code>library(raster)</code> users will be familiar with <code>stack()</code>, but in <em>terra</em> you just use the base function <code>c()</code>, like so:</p>
<div class="sourceCode" id="cb29"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb29-1"><a href="terra.html#cb29-1" tabindex="-1"></a>dstack <span class="ot">&lt;-</span> <span class="fu">c</span>(dem30, slope, aspect, hillshade)</span>
<span id="cb29-2"><a href="terra.html#cb29-2" tabindex="-1"></a></span>
<span id="cb29-3"><a href="terra.html#cb29-3" tabindex="-1"></a>dstack</span></code></pre></div>
<pre><code>## class       : SpatRaster 
## size        : 1777, 659, 4  (nrow, ncol, nlyr)
## resolution  : 30, 30  (x, y)
## extent      : -64180, -44410, -3804030, -3750720  (xmin, xmax, ymin, ymax)
## coord. ref. : GCS_WGS_1984 
## source(s)   : memory
## names       :   10m_BA,    slope,   aspect,  hillshade 
## min values  :  -15.000, 0.000000, 0.000000, -0.4906481 
## max values  : 1083.556, 1.370826, 6.283185,  0.9999974</code></pre>
<p>As you can see the “dimensions” now report 4 layers, and there are 4 names. Some of the names don’t look all that informative though, so let’s rename them.</p>
<div class="sourceCode" id="cb31"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb31-1"><a href="terra.html#cb31-1" tabindex="-1"></a><span class="fu">names</span>(dstack) <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="st">&quot;elevation&quot;</span>, <span class="st">&quot;slope&quot;</span>, <span class="st">&quot;aspect&quot;</span>, <span class="st">&quot;shade&quot;</span>)</span>
<span id="cb31-2"><a href="terra.html#cb31-2" tabindex="-1"></a></span>
<span id="cb31-3"><a href="terra.html#cb31-3" tabindex="-1"></a><span class="fu">plot</span>(dstack)</span></code></pre></div>
<p><img src="spatial-r_files/figure-html/unnamed-chunk-17-1.png" alt="" width="672" /></p>
<p><br></p>
</div>
<div id="extracting-raster-to-vector" class="section level2 hasAnchor" number="8.10">
<h2><span class="header-section-number">8.10</span> Extracting raster to vector<a href="terra.html#extracting-raster-to-vector" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>Ok, enough fooling around. More often than not, we just want to extract data from rasters for further analyses (e.g. climate layers, etc), so let’s cover that base here.</p>
<p><br></p>
<p><strong>Extract to points</strong></p>
<p>First, let’s get some points for two species in the Proteaceae, <em>Protea cynaroides</em> and <em>Leucadendron laureolum</em>…</p>
<div class="sourceCode" id="cb32"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb32-1"><a href="terra.html#cb32-1" tabindex="-1"></a><span class="fu">library</span>(rinat)</span>
<span id="cb32-2"><a href="terra.html#cb32-2" tabindex="-1"></a><span class="fu">library</span>(sf)</span></code></pre></div>
<pre><code>## Linking to GEOS 3.13.0, GDAL 3.8.5, PROJ 9.5.1; sf_use_s2() is TRUE</code></pre>
<div class="sourceCode" id="cb34"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb34-1"><a href="terra.html#cb34-1" tabindex="-1"></a><span class="co">#Call data for two species directly from iNat</span></span>
<span id="cb34-2"><a href="terra.html#cb34-2" tabindex="-1"></a>pc <span class="ot">&lt;-</span> <span class="fu">get_inat_obs</span>(<span class="at">taxon_name =</span> <span class="st">&quot;Protea cynaroides&quot;</span>,</span>
<span id="cb34-3"><a href="terra.html#cb34-3" tabindex="-1"></a>                   <span class="at">bounds =</span> <span class="fu">c</span>(<span class="sc">-</span><span class="dv">35</span>, <span class="dv">18</span>, <span class="sc">-</span><span class="fl">33.5</span>, <span class="fl">18.5</span>),</span>
<span id="cb34-4"><a href="terra.html#cb34-4" tabindex="-1"></a>                   <span class="at">maxresults =</span> <span class="dv">1000</span>)</span>
<span id="cb34-5"><a href="terra.html#cb34-5" tabindex="-1"></a></span>
<span id="cb34-6"><a href="terra.html#cb34-6" tabindex="-1"></a>ll <span class="ot">&lt;-</span> <span class="fu">get_inat_obs</span>(<span class="at">taxon_name =</span> <span class="st">&quot;Leucadendron laureolum&quot;</span>,</span>
<span id="cb34-7"><a href="terra.html#cb34-7" tabindex="-1"></a>                   <span class="at">bounds =</span> <span class="fu">c</span>(<span class="sc">-</span><span class="dv">35</span>, <span class="dv">18</span>, <span class="sc">-</span><span class="fl">33.5</span>, <span class="fl">18.5</span>),</span>
<span id="cb34-8"><a href="terra.html#cb34-8" tabindex="-1"></a>                   <span class="at">maxresults =</span> <span class="dv">1000</span>)</span>
<span id="cb34-9"><a href="terra.html#cb34-9" tabindex="-1"></a></span>
<span id="cb34-10"><a href="terra.html#cb34-10" tabindex="-1"></a><span class="co">#Combine the records into one dataframe</span></span>
<span id="cb34-11"><a href="terra.html#cb34-11" tabindex="-1"></a>pc <span class="ot">&lt;-</span> <span class="fu">rbind</span>(pc,ll)</span>
<span id="cb34-12"><a href="terra.html#cb34-12" tabindex="-1"></a></span>
<span id="cb34-13"><a href="terra.html#cb34-13" tabindex="-1"></a><span class="co">#Filter returned observations by a range of attribute criteria</span></span>
<span id="cb34-14"><a href="terra.html#cb34-14" tabindex="-1"></a>pc <span class="ot">&lt;-</span> pc <span class="sc">%&gt;%</span> <span class="fu">filter</span>(positional_accuracy<span class="sc">&lt;</span><span class="dv">46</span> <span class="sc">&amp;</span> </span>
<span id="cb34-15"><a href="terra.html#cb34-15" tabindex="-1"></a>                latitude<span class="sc">&lt;</span><span class="dv">0</span> <span class="sc">&amp;</span></span>
<span id="cb34-16"><a href="terra.html#cb34-16" tabindex="-1"></a>                <span class="sc">!</span><span class="fu">is.na</span>(latitude) <span class="sc">&amp;</span></span>
<span id="cb34-17"><a href="terra.html#cb34-17" tabindex="-1"></a>                captive_cultivated <span class="sc">==</span> <span class="st">&quot;false&quot;</span> <span class="sc">&amp;</span></span>
<span id="cb34-18"><a href="terra.html#cb34-18" tabindex="-1"></a>                quality_grade <span class="sc">==</span> <span class="st">&quot;research&quot;</span>)</span>
<span id="cb34-19"><a href="terra.html#cb34-19" tabindex="-1"></a></span>
<span id="cb34-20"><a href="terra.html#cb34-20" tabindex="-1"></a><span class="co">#Make the dataframe a spatial object of class = &quot;sf&quot;</span></span>
<span id="cb34-21"><a href="terra.html#cb34-21" tabindex="-1"></a>pc <span class="ot">&lt;-</span> <span class="fu">st_as_sf</span>(pc, <span class="at">coords =</span> <span class="fu">c</span>(<span class="st">&quot;longitude&quot;</span>, <span class="st">&quot;latitude&quot;</span>), <span class="at">crs =</span> <span class="dv">4326</span>)</span>
<span id="cb34-22"><a href="terra.html#cb34-22" tabindex="-1"></a></span>
<span id="cb34-23"><a href="terra.html#cb34-23" tabindex="-1"></a><span class="co">#Set to the same projection as the elevation data</span></span>
<span id="cb34-24"><a href="terra.html#cb34-24" tabindex="-1"></a>pc <span class="ot">&lt;-</span> <span class="fu">st_transform</span>(pc, <span class="fu">crs</span>(dem30))</span></code></pre></div>
<p>Now let’s extract the data to the points.</p>
<p>NOTE!!! <em>terra</em> doesn’t play nicely with <em>sf</em> objects at this stage, so you need to coerce them into <em>terra’s</em> own vector format using <code>vect()</code>.</p>
<div class="sourceCode" id="cb35"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb35-1"><a href="terra.html#cb35-1" tabindex="-1"></a>dat <span class="ot">&lt;-</span> terra<span class="sc">::</span><span class="fu">extract</span>(dem30, <span class="fu">vect</span>(pc)) <span class="co"># note vect()</span></span>
<span id="cb35-2"><a href="terra.html#cb35-2" tabindex="-1"></a></span>
<span id="cb35-3"><a href="terra.html#cb35-3" tabindex="-1"></a><span class="fu">head</span>(dat)</span></code></pre></div>
<pre><code>##   ID    10m_BA
## 1  1  750.5556
## 2  2  666.4444
## 3  3  765.2222
## 4  4  764.4444
## 5  5 1067.0000
## 6  6  749.3333</code></pre>
<p>Nice, but not all that handy on it’s own. Let’s add the elevation column to our points layer, so we can match it with the species names and plot.</p>
<div class="sourceCode" id="cb37"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb37-1"><a href="terra.html#cb37-1" tabindex="-1"></a>pc<span class="sc">$</span>dem <span class="ot">&lt;-</span> dat<span class="sc">$</span><span class="st">`</span><span class="at">10m_BA</span><span class="st">`</span></span>
<span id="cb37-2"><a href="terra.html#cb37-2" tabindex="-1"></a></span>
<span id="cb37-3"><a href="terra.html#cb37-3" tabindex="-1"></a>pc <span class="sc">%&gt;%</span> <span class="fu">ggplot</span>() <span class="sc">+</span></span>
<span id="cb37-4"><a href="terra.html#cb37-4" tabindex="-1"></a>  <span class="fu">geom_boxplot</span>(<span class="fu">aes</span>(scientific_name, dem))</span></code></pre></div>
<pre><code>## Warning: Removed 2 rows containing non-finite outside the scale range
## (`stat_boxplot()`).</code></pre>
<p><img src="spatial-r_files/figure-html/pc_dem_boxplot-1.png" alt="" width="672" /></p>
<p>A clear separation in the preferred elevation range between the two species.</p>
<p><br></p>
<p>Ok, that’s handy, but what if we have lots of rasters? We don’t want to have to do that for every raster! This is where raster stacks come into their own!</p>
<div class="sourceCode" id="cb39"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb39-1"><a href="terra.html#cb39-1" tabindex="-1"></a><span class="co">#extract from stack</span></span>
<span id="cb39-2"><a href="terra.html#cb39-2" tabindex="-1"></a>dat <span class="ot">&lt;-</span> terra<span class="sc">::</span><span class="fu">extract</span>(dstack, <span class="fu">vect</span>(pc)) </span>
<span id="cb39-3"><a href="terra.html#cb39-3" tabindex="-1"></a></span>
<span id="cb39-4"><a href="terra.html#cb39-4" tabindex="-1"></a><span class="co">#bind columns to points to match the names</span></span>
<span id="cb39-5"><a href="terra.html#cb39-5" tabindex="-1"></a>edat <span class="ot">&lt;-</span> <span class="fu">cbind</span>(<span class="fu">as.data.frame</span>(pc), dat)</span>
<span id="cb39-6"><a href="terra.html#cb39-6" tabindex="-1"></a></span>
<span id="cb39-7"><a href="terra.html#cb39-7" tabindex="-1"></a><span class="co">#have a quick look at the data</span></span>
<span id="cb39-8"><a href="terra.html#cb39-8" tabindex="-1"></a><span class="fu">head</span>(edat)</span></code></pre></div>
<pre><code>##     scientific_name                  datetime description
## 1 Protea cynaroides 2026-02-22 07:25:42 +0200            
## 2 Protea cynaroides 2026-02-23 07:58:39 +0200            
## 3 Protea cynaroides 2026-02-01 09:26:03 +0200            
## 4 Protea cynaroides 2026-02-01 07:06:21 +0200            
## 5 Protea cynaroides 2025-05-16 11:56:12 +0200            
## 6 Protea cynaroides 2026-02-18 10:27:00 +0200            
##                                                               place_guess
## 1                                             Cape Town, Western Cape, ZA
## 2 Kasteelspoort, Table Mountain (Nature Reserve), Cape Town, South Africa
## 3               Table Mountain National Park, Cape Town, Western Cape, ZA
## 4                       Table Mountain National Park, ZA-WC-CT, ZA-WC, ZA
## 5                                             Cape Town, Western Cape, ZA
## 6                Table Mountain (Nature Reserve), Cape Town, South Africa
##   tag_list common_name                                                url
## 1          King Protea https://www.inaturalist.org/observations/339993183
## 2          King Protea https://www.inaturalist.org/observations/339907239
## 3          King Protea https://www.inaturalist.org/observations/339868196
## 4          King Protea https://www.inaturalist.org/observations/339743109
## 5          King Protea https://www.inaturalist.org/observations/339518035
## 6          King Protea https://www.inaturalist.org/observations/339446973
##                                                                    image_url
## 1 https://inaturalist-open-data.s3.amazonaws.com/photos/618616993/medium.jpg
## 2 https://inaturalist-open-data.s3.amazonaws.com/photos/618440571/medium.jpg
## 3 https://inaturalist-open-data.s3.amazonaws.com/photos/618360202/medium.jpg
## 4 https://inaturalist-open-data.s3.amazonaws.com/photos/618103348/medium.jpg
## 5 https://inaturalist-open-data.s3.amazonaws.com/photos/617650655/medium.jpg
## 6                 https://static.inaturalist.org/photos/617504263/medium.jpg
##        user_login        id species_guess iconic_taxon_name taxon_id
## 1         grahamf 339993183  Giant Protea           Plantae   132848
## 2 justinhawthorne 339907239  Giant Protea           Plantae   132848
## 3          samshu 339868196  Giant Protea           Plantae   132848
## 4  migsgreenworld 339743109  Giant Protea           Plantae   132848
## 5      lidkaa1969 339518035   King Protea           Plantae   132848
## 6        bergwind 339446973   King Protea           Plantae   132848
##   num_identification_agreements num_identification_disagreements
## 1                             2                                0
## 2                             2                                0
## 3                             2                                0
## 4                             4                                0
## 5                             4                                0
## 6                             3                                0
##          observed_on_string observed_on        time_observed_at time_zone
## 1       2026-02-22 07:25:42  2026-02-22 2026-02-22 05:25:42 UTC  Pretoria
## 2       2026-02-23 07:58:39  2026-02-23 2026-02-23 05:58:39 UTC  Pretoria
## 3 2026-02-01 09:26:03+02:00  2026-02-01 2026-02-01 07:26:03 UTC  Pretoria
## 4 2026-02-01 07:06:21+02:00  2026-02-01 2026-02-01 05:06:21 UTC  Pretoria
## 5       2025-05-16 11:56:12  2025-05-16 2025-05-16 09:56:12 UTC  Pretoria
## 6       2026/02/18 10:27 AM  2026-02-18 2026-02-18 08:27:00 UTC  Pretoria
##   positional_accuracy public_positional_accuracy geoprivacy taxon_geoprivacy
## 1                   3                          3                        open
## 2                   4                          4                        open
## 3                   2                          2                        open
## 4                  45                         45                        open
## 5                   4                          4                        open
## 6                   4                          4                        open
##   coordinates_obscured positioning_method positioning_device  user_id
## 1                false                                        9450735
## 2                false                gps                gps  2040203
## 3                false                                        1670085
## 4                false                                        4988081
## 5                false                                       10135981
## 6                false                                         850060
##          user_name              created_at              updated_at
## 1   Graham Fehrsen 2026-02-24 05:33:03 UTC 2026-02-24 05:57:58 UTC
## 2 Justin Hawthorne 2026-02-23 16:45:36 UTC 2026-02-24 11:19:47 UTC
## 3                  2026-02-23 09:35:54 UTC 2026-02-23 12:04:12 UTC
## 4                  2026-02-22 15:42:35 UTC 2026-02-23 08:24:18 UTC
## 5            Lidia 2026-02-21 03:57:35 UTC 2026-02-23 08:24:34 UTC
## 6    Dave McDonald 2026-02-20 16:39:55 UTC 2026-02-23 08:24:31 UTC
##   quality_grade  license sound_url oauth_application_id captive_cultivated
## 1      research CC-BY-NC        NA                  843              false
## 2      research CC-BY-NC        NA                    2              false
## 3      research CC-BY-NC        NA                    3              false
## 4      research    CC-BY        NA                    3              false
## 5      research CC-BY-NC        NA                  843              false
## 6      research                 NA                   NA              false
##                     geometry       dem ID elevation      slope    aspect
## 1 POINT (-54516.04 -3760925)  750.5556  1  750.5556 0.06695751 4.4037381
## 2 POINT (-56178.58 -3760699)  666.4444  2  666.4444 0.70864517 3.8689078
## 3 POINT (-55601.45 -3760747)  765.2222  3  765.2222 0.23420278 3.8803214
## 4 POINT (-52259.22 -3758842)  764.4444  4  764.4444 0.50107646 4.0612802
## 5 POINT (-54693.01 -3759405) 1067.0000  5 1067.0000 0.12894329 0.4349015
## 6 POINT (-54526.63 -3760927)  749.3333  6  749.3333 0.05253004 3.8397131
##       shade
## 1 0.6911505
## 2 0.1931229
## 3 0.5664818
## 4 0.4143142
## 5 0.7836968
## 6 0.6776900</code></pre>
<div class="sourceCode" id="cb41"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb41-1"><a href="terra.html#cb41-1" tabindex="-1"></a><span class="co">#to make a panel plot, select columns we want and tidy data into long format</span></span>
<span id="cb41-2"><a href="terra.html#cb41-2" tabindex="-1"></a>edat <span class="ot">&lt;-</span> edat <span class="sc">%&gt;%</span> </span>
<span id="cb41-3"><a href="terra.html#cb41-3" tabindex="-1"></a>  dplyr<span class="sc">::</span><span class="fu">select</span>(scientific_name, elevation, slope, aspect, shade) <span class="sc">%&gt;%</span> </span>
<span id="cb41-4"><a href="terra.html#cb41-4" tabindex="-1"></a>  <span class="fu">pivot_longer</span>(<span class="fu">c</span>(elevation, slope, aspect, shade))</span>
<span id="cb41-5"><a href="terra.html#cb41-5" tabindex="-1"></a></span>
<span id="cb41-6"><a href="terra.html#cb41-6" tabindex="-1"></a><span class="co">#panel boxplot of the variables extracted</span></span>
<span id="cb41-7"><a href="terra.html#cb41-7" tabindex="-1"></a>edat <span class="sc">%&gt;%</span> <span class="fu">ggplot</span>() <span class="sc">+</span></span>
<span id="cb41-8"><a href="terra.html#cb41-8" tabindex="-1"></a>  <span class="fu">geom_boxplot</span>(<span class="fu">aes</span>(scientific_name, value)) <span class="sc">+</span></span>
<span id="cb41-9"><a href="terra.html#cb41-9" tabindex="-1"></a>  <span class="fu">facet_wrap</span>(<span class="sc">~</span>name, <span class="at">scales =</span> <span class="st">&quot;free&quot;</span>) </span></code></pre></div>
<pre><code>## Warning: Removed 8 rows containing non-finite outside the scale range
## (`stat_boxplot()`).</code></pre>
<p><img src="spatial-r_files/figure-html/stack_boxplot-1.png" alt="" width="672" /></p>
<p><br></p>
<p>Something I should have mentioned is that if you would like each point to sample a larger region you can add a <code>buffer =</code> argument to the <code>extract()</code> function, and a function (<code>fun =</code>) to summarize the neighbourhood of pixels sampled, like so:</p>
<div class="sourceCode" id="cb43"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb43-1"><a href="terra.html#cb43-1" tabindex="-1"></a>pc<span class="sc">$</span>dem30 <span class="ot">&lt;-</span> terra<span class="sc">::</span><span class="fu">extract</span>(dem30, <span class="fu">vect</span>(pc), <span class="at">buffer =</span> <span class="dv">200</span>, <span class="at">fun =</span> mean)<span class="sc">$</span><span class="st">`</span><span class="at">10m_BA</span><span class="st">`</span> <span class="co">#Note the sneaky use of $ to access the column I want</span></span>
<span id="cb43-2"><a href="terra.html#cb43-2" tabindex="-1"></a></span>
<span id="cb43-3"><a href="terra.html#cb43-3" tabindex="-1"></a>pc <span class="sc">%&gt;%</span> <span class="fu">ggplot</span>() <span class="sc">+</span></span>
<span id="cb43-4"><a href="terra.html#cb43-4" tabindex="-1"></a>  <span class="fu">geom_boxplot</span>(<span class="fu">aes</span>(scientific_name, dem30))</span></code></pre></div>
<pre><code>## Warning: Removed 2 rows containing non-finite outside the scale range
## (`stat_boxplot()`).</code></pre>
<p><img src="spatial-r_files/figure-html/protea_dem_boxplot-1.png" alt="" width="672" /></p>
<p><strong>Extract to polygons</strong></p>
<p>Now let’s try that with our vegetation polygons.</p>
<div class="sourceCode" id="cb45"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb45-1"><a href="terra.html#cb45-1" tabindex="-1"></a><span class="co">#Get historical vegetation layer</span></span>
<span id="cb45-2"><a href="terra.html#cb45-2" tabindex="-1"></a>veg <span class="ot">&lt;-</span> <span class="fu">st_read</span>(<span class="st">&quot;data/cape_peninsula/veg/Vegetation_Indigenous.shp&quot;</span>)</span></code></pre></div>
<pre><code>## Reading layer `Vegetation_Indigenous&#39; from data source 
##   `/Users/jasper/GIT/spatial-r/data/cape_peninsula/veg/Vegetation_Indigenous.shp&#39; 
##   using driver `ESRI Shapefile&#39;
## Simple feature collection with 1325 features and 5 fields
## Geometry type: POLYGON
## Dimension:     XY
## Bounding box:  xmin: -63972.95 ymin: -3803535 xmax: 430.8125 ymax: -3705149
## Projected CRS: WGS_1984_Transverse_Mercator</code></pre>
<div class="sourceCode" id="cb47"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb47-1"><a href="terra.html#cb47-1" tabindex="-1"></a><span class="co">#Crop to same extent as DEM</span></span>
<span id="cb47-2"><a href="terra.html#cb47-2" tabindex="-1"></a>veg <span class="ot">&lt;-</span> <span class="fu">st_crop</span>(veg, <span class="fu">ext</span>(dem30)) <span class="co">#Note that I just fed it the extent of the DEM</span></span></code></pre></div>
<pre><code>## Warning: attribute variables are assumed to be spatially constant throughout
## all geometries</code></pre>
<div class="sourceCode" id="cb49"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb49-1"><a href="terra.html#cb49-1" tabindex="-1"></a><span class="co">#Best to dissolve polygons first - otherwise you get repeat outputs for each polygon within each veg type</span></span>
<span id="cb49-2"><a href="terra.html#cb49-2" tabindex="-1"></a>vegsum <span class="ot">&lt;-</span> veg <span class="sc">%&gt;%</span> <span class="fu">group_by</span>(National_) <span class="sc">%&gt;%</span> </span>
<span id="cb49-3"><a href="terra.html#cb49-3" tabindex="-1"></a>  <span class="fu">summarize</span>()</span>
<span id="cb49-4"><a href="terra.html#cb49-4" tabindex="-1"></a></span>
<span id="cb49-5"><a href="terra.html#cb49-5" tabindex="-1"></a><span class="co">#Do extraction - note the summary function</span></span>
<span id="cb49-6"><a href="terra.html#cb49-6" tabindex="-1"></a>vegdem <span class="ot">&lt;-</span> terra<span class="sc">::</span><span class="fu">extract</span>(dem30, <span class="fu">vect</span>(vegsum), <span class="at">fun =</span> mean, <span class="at">na.rm =</span> T)</span></code></pre></div>
<pre><code>## Warning: [extract] transforming vector data to the CRS of the raster</code></pre>
<div class="sourceCode" id="cb51"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb51-1"><a href="terra.html#cb51-1" tabindex="-1"></a><span class="co">#Combine the names and vector extracted means into a dataframe</span></span>
<span id="cb51-2"><a href="terra.html#cb51-2" tabindex="-1"></a>vegdem <span class="ot">&lt;-</span> <span class="fu">cbind</span>(vegdem, vegsum<span class="sc">$</span>National_)</span>
<span id="cb51-3"><a href="terra.html#cb51-3" tabindex="-1"></a></span>
<span id="cb51-4"><a href="terra.html#cb51-4" tabindex="-1"></a><span class="co">#Rename the columns to something meaningful</span></span>
<span id="cb51-5"><a href="terra.html#cb51-5" tabindex="-1"></a><span class="fu">names</span>(vegdem) <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="st">&quot;ID&quot;</span>, <span class="st">&quot;Mean elevation (m)&quot;</span>, <span class="st">&quot;Vegetation type&quot;</span>)</span>
<span id="cb51-6"><a href="terra.html#cb51-6" tabindex="-1"></a></span>
<span id="cb51-7"><a href="terra.html#cb51-7" tabindex="-1"></a><span class="co">#Plot</span></span>
<span id="cb51-8"><a href="terra.html#cb51-8" tabindex="-1"></a>vegdem <span class="sc">%&gt;%</span> <span class="fu">ggplot</span>() <span class="sc">+</span></span>
<span id="cb51-9"><a href="terra.html#cb51-9" tabindex="-1"></a>  <span class="fu">geom_col</span>(<span class="fu">aes</span>(<span class="at">y =</span> <span class="st">`</span><span class="at">Mean elevation (m)</span><span class="st">`</span>, <span class="at">x =</span> <span class="st">`</span><span class="at">Vegetation type</span><span class="st">`</span>)) <span class="sc">+</span></span>
<span id="cb51-10"><a href="terra.html#cb51-10" tabindex="-1"></a>  <span class="fu">theme</span>(<span class="at">axis.text.x =</span> <span class="fu">element_text</span>(<span class="at">angle =</span> <span class="dv">90</span>, <span class="at">vjust =</span> <span class="fl">0.5</span>, <span class="at">hjust=</span><span class="dv">1</span>))</span></code></pre></div>
<p><img src="spatial-r_files/figure-html/dem_hist-1.png" alt="" width="672" /></p>
<p>Ok, I did a lot of things there…, but you get it right? Note that I applied a function to the <code>extract()</code> to summarize the output, because each polygon usually returns multiple raster cell values. You can choose (or code up) your own function.</p>
<p><br></p>
<p>Here’s a different approach…</p>
<p><br></p>
</div>
<div id="rasterizing" class="section level2 hasAnchor" number="8.11">
<h2><span class="header-section-number">8.11</span> Rasterizing<a href="terra.html#rasterizing" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p><em>Rasterizing</em> essentially means turning a vector layer into a raster. To rasterize, you need an existing raster grid to rasterize to, like <code>dem30</code> in this case.</p>
<div class="sourceCode" id="cb52"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb52-1"><a href="terra.html#cb52-1" tabindex="-1"></a><span class="co">#Make the vegetation type a factor</span></span>
<span id="cb52-2"><a href="terra.html#cb52-2" tabindex="-1"></a>vegsum<span class="sc">$</span>National_ <span class="ot">&lt;-</span> <span class="fu">as.factor</span>(vegsum<span class="sc">$</span>National_)</span>
<span id="cb52-3"><a href="terra.html#cb52-3" tabindex="-1"></a></span>
<span id="cb52-4"><a href="terra.html#cb52-4" tabindex="-1"></a><span class="co">#Rasterize</span></span>
<span id="cb52-5"><a href="terra.html#cb52-5" tabindex="-1"></a>vegras <span class="ot">&lt;-</span> <span class="fu">rasterize</span>(<span class="fu">vect</span>(vegsum), dem30, <span class="at">field =</span> <span class="st">&quot;National_&quot;</span>)</span>
<span id="cb52-6"><a href="terra.html#cb52-6" tabindex="-1"></a></span>
<span id="cb52-7"><a href="terra.html#cb52-7" tabindex="-1"></a><span class="co">#Plot</span></span>
<span id="cb52-8"><a href="terra.html#cb52-8" tabindex="-1"></a>vegras <span class="sc">%&gt;%</span> </span>
<span id="cb52-9"><a href="terra.html#cb52-9" tabindex="-1"></a>  <span class="fu">as.data.frame</span>(<span class="at">xy =</span> <span class="cn">TRUE</span>) <span class="sc">%&gt;%</span></span>
<span id="cb52-10"><a href="terra.html#cb52-10" tabindex="-1"></a>  <span class="fu">ggplot</span>() <span class="sc">+</span></span>
<span id="cb52-11"><a href="terra.html#cb52-11" tabindex="-1"></a>  <span class="fu">geom_raster</span>(<span class="fu">aes</span>(<span class="at">x =</span> x, <span class="at">y =</span> y, <span class="at">fill =</span> National_))</span></code></pre></div>
<p><img src="spatial-r_files/figure-html/penviz-1.png" alt="" width="528" /></p>
<p>I’m sure this plot is a surprise to those who worked with <em>raster</em>. Usually rasters want to work with numbers. <em>terra</em> can work with (and rasterize) data of class “factor”, opening up all kinds of opportunities.</p>
<p><br></p>
<p>But once you have a raster of class factor and a raster with values, you can stack and unpack them into a dataframe and analyse them as you would usually.</p>
<p><br></p>
<div class="sourceCode" id="cb53"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb53-1"><a href="terra.html#cb53-1" tabindex="-1"></a><span class="co">#Stack the two rasters</span></span>
<span id="cb53-2"><a href="terra.html#cb53-2" tabindex="-1"></a>vegdem <span class="ot">&lt;-</span> <span class="fu">c</span>(vegras, dem30) </span>
<span id="cb53-3"><a href="terra.html#cb53-3" tabindex="-1"></a></span>
<span id="cb53-4"><a href="terra.html#cb53-4" tabindex="-1"></a><span class="co">#Convert to data frame</span></span>
<span id="cb53-5"><a href="terra.html#cb53-5" tabindex="-1"></a>vegdem_df <span class="ot">&lt;-</span> <span class="fu">as.data.frame</span>(vegdem) </span>
<span id="cb53-6"><a href="terra.html#cb53-6" tabindex="-1"></a></span>
<span id="cb53-7"><a href="terra.html#cb53-7" tabindex="-1"></a><span class="co">#Plot</span></span>
<span id="cb53-8"><a href="terra.html#cb53-8" tabindex="-1"></a>vegdem_df <span class="sc">%&gt;%</span> </span>
<span id="cb53-9"><a href="terra.html#cb53-9" tabindex="-1"></a>  <span class="fu">group_by</span>(National_) <span class="sc">%&gt;%</span></span>
<span id="cb53-10"><a href="terra.html#cb53-10" tabindex="-1"></a>  <span class="fu">summarise</span>(<span class="st">`</span><span class="at">Mean elevation (m)</span><span class="st">`</span> <span class="ot">=</span> <span class="fu">mean</span>(<span class="st">`</span><span class="at">10m_BA</span><span class="st">`</span>, <span class="at">na.rm =</span> T)) <span class="sc">%&gt;%</span></span>
<span id="cb53-11"><a href="terra.html#cb53-11" tabindex="-1"></a>  <span class="fu">ggplot</span>() <span class="sc">+</span></span>
<span id="cb53-12"><a href="terra.html#cb53-12" tabindex="-1"></a>  <span class="fu">geom_col</span>(<span class="fu">aes</span>(<span class="at">y =</span> <span class="st">`</span><span class="at">Mean elevation (m)</span><span class="st">`</span>, <span class="at">x =</span> <span class="st">`</span><span class="at">National_</span><span class="st">`</span>)) <span class="sc">+</span></span>
<span id="cb53-13"><a href="terra.html#cb53-13" tabindex="-1"></a>  <span class="fu">theme</span>(<span class="at">axis.text.x =</span> <span class="fu">element_text</span>(<span class="at">angle =</span> <span class="dv">90</span>, <span class="at">vjust =</span> <span class="fl">0.5</span>, <span class="at">hjust=</span><span class="dv">1</span>))</span></code></pre></div>
<p><img src="spatial-r_files/figure-html/unnamed-chunk-19-1.png" alt="" width="672" /></p>
<p><br></p>
<p>Tadaa! Same figure we made before, but we took a different route this time. Note that the second approach doesn’t require us to summarize the raster values for each polygon first, because we can just convert the whole stack to a dataframe and do the summary (if we want it) in R with <em>dplyr</em> instead. This is a powerful way to work with rasters, and allows you to use all the tools of the <em>Tidyverse</em> for data manipulation and visualization.</p>
<p><br></p>
<div class="sourceCode" id="cb54"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb54-1"><a href="terra.html#cb54-1" tabindex="-1"></a><span class="co"># #Plot</span></span>
<span id="cb54-2"><a href="terra.html#cb54-2" tabindex="-1"></a></span>
<span id="cb54-3"><a href="terra.html#cb54-3" tabindex="-1"></a><span class="fu">library</span>(ggridges)</span>
<span id="cb54-4"><a href="terra.html#cb54-4" tabindex="-1"></a></span>
<span id="cb54-5"><a href="terra.html#cb54-5" tabindex="-1"></a>vegdem_df <span class="sc">%&gt;%</span> <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x =</span> <span class="st">`</span><span class="at">10m_BA</span><span class="st">`</span>, <span class="at">y =</span> <span class="st">`</span><span class="at">National_</span><span class="st">`</span>, <span class="at">fill =</span> <span class="st">`</span><span class="at">National_</span><span class="st">`</span>)) <span class="sc">+</span></span>
<span id="cb54-6"><a href="terra.html#cb54-6" tabindex="-1"></a>  <span class="fu">geom_density_ridges</span>() <span class="sc">+</span></span>
<span id="cb54-7"><a href="terra.html#cb54-7" tabindex="-1"></a>  <span class="fu">theme_ridges</span>() <span class="sc">+</span> </span>
<span id="cb54-8"><a href="terra.html#cb54-8" tabindex="-1"></a>  <span class="fu">theme</span>(<span class="at">legend.position =</span> <span class="st">&quot;none&quot;</span>) <span class="sc">+</span></span>
<span id="cb54-9"><a href="terra.html#cb54-9" tabindex="-1"></a>  <span class="fu">theme</span>(<span class="at">axis.text.x =</span> <span class="fu">element_text</span>(<span class="at">angle =</span> <span class="dv">90</span>, <span class="at">vjust =</span> <span class="fl">0.5</span>, <span class="at">hjust=</span><span class="dv">1</span>)) <span class="sc">+</span></span>
<span id="cb54-10"><a href="terra.html#cb54-10" tabindex="-1"></a>  <span class="fu">xlim</span>(<span class="dv">0</span>, <span class="dv">300</span>) <span class="sc">+</span></span>
<span id="cb54-11"><a href="terra.html#cb54-11" tabindex="-1"></a>  <span class="fu">xlab</span>(<span class="st">&quot;Elevation (m)&quot;</span>) <span class="sc">+</span></span>
<span id="cb54-12"><a href="terra.html#cb54-12" tabindex="-1"></a>  <span class="fu">ylab</span>(<span class="st">&quot;Vegetation type&quot;</span>)</span></code></pre></div>
<pre><code>## Picking joint bandwidth of 4.05</code></pre>
<p><img src="spatial-r_files/figure-html/unnamed-chunk-20-1.png" alt="" width="672" /></p>
<p><br></p>
<p>The ability to turn stacked rasters into dataframes and analyse them “non-spatially” can be very powerful. There are also a bunch of functions that make this even easier.</p>
<p><br></p>
</div>
<div id="crosstabulating-rasters" class="section level2 hasAnchor" number="8.12">
<h2><span class="header-section-number">8.12</span> Crosstabulating rasters<a href="terra.html#crosstabulating-rasters" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>Say we had two or more rasters that each contained factor data (i.e. discrete) and we wanted to look at the frequency of associations between the different sets of classes? We can very easily do this with the function <code>crosstab()</code>.</p>
<p>Here’s an example looking at slope classes by vegetation type. First, we classify our slope raster into discrete classes, then we cross-tabulate the classified slope raster with our raster of vegetation types.</p>
<p><br></p>
<div class="sourceCode" id="cb56"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb56-1"><a href="terra.html#cb56-1" tabindex="-1"></a><span class="co"># Classify the slope raster into 5 classes</span></span>
<span id="cb56-2"><a href="terra.html#cb56-2" tabindex="-1"></a>slopeclass <span class="ot">&lt;-</span> <span class="fu">classify</span>(slope, <span class="fu">c</span>(<span class="dv">0</span>, <span class="fl">0.3</span>, <span class="fl">0.6</span>, <span class="fl">0.9</span>, <span class="fl">1.2</span>, <span class="fl">1.4</span>), <span class="at">include.lowest=</span><span class="cn">TRUE</span>)</span>
<span id="cb56-3"><a href="terra.html#cb56-3" tabindex="-1"></a>aspectclass <span class="ot">&lt;-</span>  <span class="fu">classify</span>(aspect, <span class="fu">c</span>(<span class="dv">0</span>, <span class="dv">2</span>, <span class="dv">4</span>, <span class="fl">6.5</span>), <span class="at">include.lowest=</span><span class="cn">TRUE</span>)</span>
<span id="cb56-4"><a href="terra.html#cb56-4" tabindex="-1"></a></span>
<span id="cb56-5"><a href="terra.html#cb56-5" tabindex="-1"></a><span class="fu">plot</span>(slopeclass)</span></code></pre></div>
<p><img src="spatial-r_files/figure-html/unnamed-chunk-21-1.png" alt="" width="672" /></p>
<div class="sourceCode" id="cb57"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb57-1"><a href="terra.html#cb57-1" tabindex="-1"></a><span class="co"># Crosstabulate slope with veg type</span></span>
<span id="cb57-2"><a href="terra.html#cb57-2" tabindex="-1"></a><span class="fu">crosstab</span>(<span class="fu">c</span>(vegras, slopeclass, aspectclass))</span></code></pre></div>
<pre><code>## , , aspect = (2 - 4]
## 
##                                          slope
## National_                                 (0.3 - 0.6] (0.6 - 0.9] (0.9 - 1.2]
##   Beach - FalseBay                                277          84          29
##   Cape Estuarine Salt Marshes                       0           0           0
##   Cape Flats Dune Strandveld - False Bay         1413         317          31
##   Cape Flats Dune Strandveld - West Coast           0           0           0
##   Cape Flats Sand Fynbos                            0           0           0
##   Cape Lowland Freshwater Wetlands                  0           0           0
##   Hangklip Sand Fynbos                           1835         133           6
##   Peninsula Granite Fynbos - North                993          87           0
##   Peninsula Granite Fynbos - South               3980         850         151
##   Peninsula Sandstone Fynbos                    19730        6198        1207
##   Peninsula Shale Fynbos                          579         148          21
##   Peninsula Shale Renosterveld                    619           0           0
##   RECLAIMED                                        21           3           0
##   Southern Afrotemperate Forest                  1303         374          57
##                                          slope
## National_                                 (1.2 - 1.4] [0 - 0.3]
##   Beach - FalseBay                                  0      1568
##   Cape Estuarine Salt Marshes                       0        54
##   Cape Flats Dune Strandveld - False Bay            0     13349
##   Cape Flats Dune Strandveld - West Coast           0      1741
##   Cape Flats Sand Fynbos                            0     33815
##   Cape Lowland Freshwater Wetlands                  0      1558
##   Hangklip Sand Fynbos                              0     10325
##   Peninsula Granite Fynbos - North                  0       546
##   Peninsula Granite Fynbos - South                 16     22278
##   Peninsula Sandstone Fynbos                       55     50268
##   Peninsula Shale Fynbos                            0      4404
##   Peninsula Shale Renosterveld                      0      2635
##   RECLAIMED                                         0      2060
##   Southern Afrotemperate Forest                     3      1058
## 
## , , aspect = (4 - 6.5]
## 
##                                          slope
## National_                                 (0.3 - 0.6] (0.6 - 0.9] (0.9 - 1.2]
##   Beach - FalseBay                                 66          65           8
##   Cape Estuarine Salt Marshes                       0           0           0
##   Cape Flats Dune Strandveld - False Bay          946         147           8
##   Cape Flats Dune Strandveld - West Coast           0           0           0
##   Cape Flats Sand Fynbos                            0           0           0
##   Cape Lowland Freshwater Wetlands                  0           0           0
##   Hangklip Sand Fynbos                            277           2           0
##   Peninsula Granite Fynbos - North               8096         364           3
##   Peninsula Granite Fynbos - South               4597         830         127
##   Peninsula Sandstone Fynbos                    17091        6209        1621
##   Peninsula Shale Fynbos                          784          11           0
##   Peninsula Shale Renosterveld                   1065          56           0
##   RECLAIMED                                         6           0           0
##   Southern Afrotemperate Forest                   144          43          19
##                                          slope
## National_                                 (1.2 - 1.4] [0 - 0.3]
##   Beach - FalseBay                                  0       776
##   Cape Estuarine Salt Marshes                       0        28
##   Cape Flats Dune Strandveld - False Bay            0     16054
##   Cape Flats Dune Strandveld - West Coast           0      2739
##   Cape Flats Sand Fynbos                            0     29762
##   Cape Lowland Freshwater Wetlands                  0      3498
##   Hangklip Sand Fynbos                              0     15284
##   Peninsula Granite Fynbos - North                  0      8633
##   Peninsula Granite Fynbos - South                  0     13365
##   Peninsula Sandstone Fynbos                       67     61386
##   Peninsula Shale Fynbos                            0      1001
##   Peninsula Shale Renosterveld                      0      9381
##   RECLAIMED                                         0      2119
##   Southern Afrotemperate Forest                     0       180
## 
## , , aspect = [0 - 2]
## 
##                                          slope
## National_                                 (0.3 - 0.6] (0.6 - 0.9] (0.9 - 1.2]
##   Beach - FalseBay                                 17          16           3
##   Cape Estuarine Salt Marshes                       0           0           0
##   Cape Flats Dune Strandveld - False Bay          531         356          62
##   Cape Flats Dune Strandveld - West Coast           0           0           0
##   Cape Flats Sand Fynbos                            3           0           0
##   Cape Lowland Freshwater Wetlands                  0           0           0
##   Hangklip Sand Fynbos                            707           6           2
##   Peninsula Granite Fynbos - North               1948          57           5
##   Peninsula Granite Fynbos - South               4848         399          57
##   Peninsula Sandstone Fynbos                    21704        8267        1339
##   Peninsula Shale Fynbos                         1626         181          24
##   Peninsula Shale Renosterveld                    757          11           0
##   RECLAIMED                                         9           0           0
##   Southern Afrotemperate Forest                   301          66           2
##                                          slope
## National_                                 (1.2 - 1.4] [0 - 0.3]
##   Beach - FalseBay                                  0       263
##   Cape Estuarine Salt Marshes                       0        41
##   Cape Flats Dune Strandveld - False Bay            0     12030
##   Cape Flats Dune Strandveld - West Coast           0      2682
##   Cape Flats Sand Fynbos                            0     45363
##   Cape Lowland Freshwater Wetlands                  0      1548
##   Hangklip Sand Fynbos                              0      8038
##   Peninsula Granite Fynbos - North                  0      2266
##   Peninsula Granite Fynbos - South                  0     27984
##   Peninsula Sandstone Fynbos                       69     48492
##   Peninsula Shale Fynbos                            0      5255
##   Peninsula Shale Renosterveld                      0     11953
##   RECLAIMED                                         0      2257
##   Southern Afrotemperate Forest                     0       296</code></pre>
<p><br></p>
<p>This function is particularly useful for something like comparing land cover datasets from 2 time points. Also have a look at <code>freq</code> and <code>zonal</code>.</p>
<p><br></p>
</div>
<div id="visualizing-multiple-datasets-on-one-map" class="section level2 hasAnchor" number="8.13">
<h2><span class="header-section-number">8.13</span> Visualizing multiple datasets on one map<a href="terra.html#visualizing-multiple-datasets-on-one-map" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>What about if we want to plot multiple datasets on one map?</p>
<p>This is easy, if you can feed each dataset into a separate ggplot function. Here’s the veg types with contours and the iNaturalist records we retrieved earlier.</p>
<div class="sourceCode" id="cb59"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb59-1"><a href="terra.html#cb59-1" tabindex="-1"></a><span class="fu">ggplot</span>() <span class="sc">+</span></span>
<span id="cb59-2"><a href="terra.html#cb59-2" tabindex="-1"></a>  <span class="fu">geom_raster</span>(<span class="at">data =</span> <span class="fu">as.data.frame</span>(vegras, <span class="at">xy =</span> <span class="cn">TRUE</span>),</span>
<span id="cb59-3"><a href="terra.html#cb59-3" tabindex="-1"></a>              <span class="fu">aes</span>(<span class="at">x =</span> x, <span class="at">y =</span> y, <span class="at">fill =</span> National_)) <span class="sc">+</span></span>
<span id="cb59-4"><a href="terra.html#cb59-4" tabindex="-1"></a>  <span class="fu">geom_contour</span>(<span class="at">data =</span> <span class="fu">as.data.frame</span>(dem30, <span class="at">xy =</span> <span class="cn">TRUE</span>), </span>
<span id="cb59-5"><a href="terra.html#cb59-5" tabindex="-1"></a>               <span class="fu">aes</span>(<span class="at">x =</span> x, <span class="at">y =</span> y, <span class="at">z =</span> <span class="st">`</span><span class="at">10m_BA</span><span class="st">`</span>), <span class="at">breaks =</span> <span class="fu">seq</span>(<span class="dv">0</span>, <span class="dv">1100</span>, <span class="dv">100</span>), <span class="at">colour =</span> <span class="st">&quot;black&quot;</span>) <span class="sc">+</span></span>
<span id="cb59-6"><a href="terra.html#cb59-6" tabindex="-1"></a>  <span class="fu">geom_sf</span>(<span class="at">data=</span>pc, <span class="at">colour =</span> <span class="st">&quot;white&quot;</span>, <span class="at">size =</span> <span class="fl">0.5</span>)</span></code></pre></div>
<p><img src="spatial-r_files/figure-html/penviz_multi-1.png" alt="" width="576" /></p>
<p>For more inspiration on mapping with R, check out <a href="https://slingsby-maps.myshopify.com/" class="uri">https://slingsby-maps.myshopify.com/</a>. I’ve been generating the majority of the basemap (terrain colour, hillshade, contours, streams, etc) for these in R for the past few years.</p>
<p><br></p>
</div>
<div id="cloud-optimized-geotiffs-cogs" class="section level2 hasAnchor" number="8.14">
<h2><span class="header-section-number">8.14</span> Cloud Optimized GeoTiffs (COGs)!!!<a href="terra.html#cloud-optimized-geotiffs-cogs" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>I thought I’d add this as a bonus section, reinforcing the value of standardized open metadata and file formats from the <a href="https://www.ecologi.st/data-management/data.html#describe">Data Management</a> module.</p>
<p>First, let’s open a connection to our COG, which is stored in the cloud. To do this, we need to pass a URL to the file’s online location to <em>terra</em>.</p>
<div class="sourceCode" id="cb60"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb60-1"><a href="terra.html#cb60-1" tabindex="-1"></a>cog.url <span class="ot">&lt;-</span> <span class="st">&quot;/vsicurl/https://mnemosyne.somisana.ac.za/osgeo/saeon_rgb/grootbos.tif&quot;</span></span>
<span id="cb60-2"><a href="terra.html#cb60-2" tabindex="-1"></a></span>
<span id="cb60-3"><a href="terra.html#cb60-3" tabindex="-1"></a>grootbos <span class="ot">&lt;-</span> <span class="fu">rast</span>(cog.url)</span>
<span id="cb60-4"><a href="terra.html#cb60-4" tabindex="-1"></a></span>
<span id="cb60-5"><a href="terra.html#cb60-5" tabindex="-1"></a>grootbos</span></code></pre></div>
<pre><code>## class       : SpatRaster 
## size        : 100024, 121627, 3  (nrow, ncol, nlyr)
## resolution  : 0.08, 0.08  (x, y)
## extent      : 35640.41, 45370.57, -3828176, -3820175  (xmin, xmax, ymin, ymax)
## coord. ref. : LO19 
## source      : grootbos.tif 
## colors RGB  : 1, 2, 3 
## names       : grootbos_1, grootbos_2, grootbos_3</code></pre>
<p>This has given us the metadata about the file, but has not read it into R’s memory. The file is ~1.8GB so it would do bad things if we tried to read the whole thing in…</p>
<p>Now let’s retrieve a subset of the file. To do this we need to make a vector polygon for our region of interest (ROI), like so:</p>
<div class="sourceCode" id="cb62"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb62-1"><a href="terra.html#cb62-1" tabindex="-1"></a>roi <span class="ot">&lt;-</span> <span class="fu">vect</span>(<span class="fu">data.frame</span>(<span class="at">lon =</span> <span class="fu">c</span>(<span class="fl">19.433975</span>, <span class="fl">19.436451</span>),</span>
<span id="cb62-2"><a href="terra.html#cb62-2" tabindex="-1"></a>                       <span class="at">lat =</span> <span class="fu">c</span>(<span class="sc">-</span><span class="fl">34.522733</span>, <span class="sc">-</span><span class="fl">34.520735</span>)),</span>
<span id="cb62-3"><a href="terra.html#cb62-3" tabindex="-1"></a>            <span class="at">crs =</span> <span class="st">&quot;epsg:4326&quot;</span>)</span></code></pre></div>
<p>And transform it to the same projection as the COG:</p>
<div class="sourceCode" id="cb63"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb63-1"><a href="terra.html#cb63-1" tabindex="-1"></a>roi <span class="ot">&lt;-</span> terra<span class="sc">::</span><span class="fu">project</span>(roi, <span class="fu">crs</span>(grootbos))</span></code></pre></div>
<p>And then extract our ROI</p>
<div class="sourceCode" id="cb64"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb64-1"><a href="terra.html#cb64-1" tabindex="-1"></a>roi_ras <span class="ot">&lt;-</span> <span class="fu">crop</span>(grootbos, roi)</span>
<span id="cb64-2"><a href="terra.html#cb64-2" tabindex="-1"></a></span>
<span id="cb64-3"><a href="terra.html#cb64-3" tabindex="-1"></a>roi_ras</span></code></pre></div>
<pre><code>## class       : SpatRaster 
## size        : 2758, 2853, 3  (nrow, ncol, nlyr)
## resolution  : 0.08, 0.08  (x, y)
## extent      : 39845.61, 40073.85, -3821732, -3821512  (xmin, xmax, ymin, ymax)
## coord. ref. : LO19 
## source(s)   : memory
## colors RGB  : 1, 2, 3 
## varname     : grootbos 
## names       : grootbos_1, grootbos_2, grootbos_3 
## min values  :         28,         47,         56 
## max values  :        255,        255,        255</code></pre>
<p>Now we have a raster with 3 layers in memory. There are Red Green and Blue, so we should be able to plot them, like so:</p>
<div class="sourceCode" id="cb66"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb66-1"><a href="terra.html#cb66-1" tabindex="-1"></a><span class="fu">plotRGB</span>(roi_ras)</span></code></pre></div>
<p><img src="spatial-r_files/figure-html/plot_cog-1.png" alt="" width="672" /></p>
<p>This somewhat arbitrary looking site is where we did some fieldwork in the Grootbos Private Nature Reserve with the 2022 class…</p>
<p><br></p>
</div>
<div id="obtaining-satellite-data-from-apis" class="section level2 hasAnchor" number="8.15">
<h2><span class="header-section-number">8.15</span> Obtaining satellite data from APIs<a href="terra.html#obtaining-satellite-data-from-apis" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>There are also R packages like <a href="https://cran.r-project.org/web/packages/MODISTools/index.html">MODISTools</a> that allow you to query the online databases.</p>
<p>MODISTools interfaces with the ‘MODIS Land Products Subsets’ Web Services to download various products. In this case we’ll be downloading the “MOD13Q1” product, which is the Vegetation Indices product for the Terra satellite, generated every 16 days at 250 meter (m) spatial resolution. The algorithm chooses the best available pixel value from all (daily) the acquisitions from the 16 day period, minimizing clouds, low view angle, and selecting the highest NDVI/EVI value.</p>
<p>WARNING! This code can take a while to run! Hence, I have wrapped it in an <code>if()</code> statement that tells the code not to run if the file already exists.</p>
<div class="sourceCode" id="cb67"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb67-1"><a href="terra.html#cb67-1" tabindex="-1"></a><span class="cf">if</span>(<span class="sc">!</span><span class="fu">file.exists</span>(<span class="st">&quot;data/MODISdat_batch_30Jan2023.csv&quot;</span>)) <span class="co"># if the file does not exist, then run... otherwise do nothing...</span></span>
<span id="cb67-2"><a href="terra.html#cb67-2" tabindex="-1"></a>  {</span>
<span id="cb67-3"><a href="terra.html#cb67-3" tabindex="-1"></a></span>
<span id="cb67-4"><a href="terra.html#cb67-4" tabindex="-1"></a><span class="fu">library</span>(MODISTools)</span>
<span id="cb67-5"><a href="terra.html#cb67-5" tabindex="-1"></a></span>
<span id="cb67-6"><a href="terra.html#cb67-6" tabindex="-1"></a>sites <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(<span class="at">site_name =</span> <span class="fu">c</span>(<span class="st">&quot;grassy field&quot;</span>, <span class="st">&quot;invasion&quot;</span>, <span class="st">&quot;renosterveld&quot;</span>, <span class="st">&quot;sand&quot;</span>, <span class="st">&quot;sandstone&quot;</span>, <span class="st">&quot;limestone&quot;</span>),</span>
<span id="cb67-7"><a href="terra.html#cb67-7" tabindex="-1"></a>                    <span class="at">lat =</span> <span class="fu">c</span>(<span class="sc">-</span><span class="fl">34.375052</span>, <span class="sc">-</span><span class="fl">34.386014</span>, <span class="sc">-</span><span class="fl">34.374259</span>, <span class="sc">-</span><span class="fl">34.3961</span>, <span class="sc">-</span><span class="fl">34.3748</span>, <span class="sc">-</span><span class="fl">34.4309</span>),</span>
<span id="cb67-8"><a href="terra.html#cb67-8" tabindex="-1"></a>                    <span class="at">lon =</span> <span class="fu">c</span>(<span class="fl">20.531749</span>, <span class="fl">20.534986</span>, <span class="fl">20.504233</span>, <span class="fl">20.5494</span>, <span class="fl">20.5428</span>, <span class="fl">20.5666</span>))</span>
<span id="cb67-9"><a href="terra.html#cb67-9" tabindex="-1"></a></span>
<span id="cb67-10"><a href="terra.html#cb67-10" tabindex="-1"></a><span class="do">### Here&#39;s some code if you want to use an existing layer of points instead of entering them manually</span></span>
<span id="cb67-11"><a href="terra.html#cb67-11" tabindex="-1"></a><span class="co"># sites &lt;- st_read(&quot;/home/jasper/GIT/BIO3018F/prac/Potberg_prac_sites.kml&quot;)</span></span>
<span id="cb67-12"><a href="terra.html#cb67-12" tabindex="-1"></a><span class="co"># sites &lt;- data.frame(site_name = sites$Name, lat = st_coordinates(sites)[,2], lon = st_coordinates(sites)[,1])</span></span>
<span id="cb67-13"><a href="terra.html#cb67-13" tabindex="-1"></a></span>
<span id="cb67-14"><a href="terra.html#cb67-14" tabindex="-1"></a>dat <span class="ot">&lt;-</span> <span class="fu">mt_batch_subset</span>(<span class="at">df =</span> sites,</span>
<span id="cb67-15"><a href="terra.html#cb67-15" tabindex="-1"></a>                        <span class="at">product =</span> <span class="st">&quot;MOD13Q1&quot;</span>,</span>
<span id="cb67-16"><a href="terra.html#cb67-16" tabindex="-1"></a>                        <span class="at">band =</span> <span class="st">&quot;250m_16_days_NDVI&quot;</span>,</span>
<span id="cb67-17"><a href="terra.html#cb67-17" tabindex="-1"></a>                        <span class="at">internal =</span> <span class="cn">TRUE</span>,</span>
<span id="cb67-18"><a href="terra.html#cb67-18" tabindex="-1"></a>                        <span class="at">start =</span> <span class="st">&quot;2000-01-01&quot;</span>,</span>
<span id="cb67-19"><a href="terra.html#cb67-19" tabindex="-1"></a>                        <span class="at">end =</span> <span class="st">&quot;2023-01-30&quot;</span>)</span>
<span id="cb67-20"><a href="terra.html#cb67-20" tabindex="-1"></a></span>
<span id="cb67-21"><a href="terra.html#cb67-21" tabindex="-1"></a><span class="fu">write_csv</span>(dat, <span class="st">&quot;data/MODISdat_batch_30Jan2023.csv&quot;</span>)</span>
<span id="cb67-22"><a href="terra.html#cb67-22" tabindex="-1"></a>}</span></code></pre></div>
<p>Plot all time series</p>
<div class="sourceCode" id="cb68"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb68-1"><a href="terra.html#cb68-1" tabindex="-1"></a><span class="fu">read_csv</span>(<span class="st">&quot;data/MODISdat_batch_30Jan2023.csv&quot;</span>) <span class="sc">%&gt;%</span></span>
<span id="cb68-2"><a href="terra.html#cb68-2" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x =</span> calendar_date, <span class="at">y =</span> value<span class="sc">*</span><span class="fl">0.0001</span>)) <span class="sc">+</span></span>
<span id="cb68-3"><a href="terra.html#cb68-3" tabindex="-1"></a>  <span class="fu">geom_line</span>() <span class="sc">+</span></span>
<span id="cb68-4"><a href="terra.html#cb68-4" tabindex="-1"></a>  <span class="co">#  geom_point() +</span></span>
<span id="cb68-5"><a href="terra.html#cb68-5" tabindex="-1"></a>  <span class="fu">facet_wrap</span>(.<span class="sc">~</span> site) <span class="sc">+</span></span>
<span id="cb68-6"><a href="terra.html#cb68-6" tabindex="-1"></a>  <span class="fu">ylab</span>(<span class="st">&quot;NDVI&quot;</span>) <span class="sc">+</span></span>
<span id="cb68-7"><a href="terra.html#cb68-7" tabindex="-1"></a>  <span class="fu">ylim</span>(<span class="fl">0.2</span>, <span class="fl">0.9</span>)</span></code></pre></div>
<pre><code>## Warning: Removed 1 row containing missing values or values outside the scale range
## (`geom_line()`).</code></pre>
<p><img src="spatial-r_files/figure-html/modis_plot-1.png" alt="" width="672" /></p>
<p>There are many more complex spatial and remote sensing analyses you can do by interaction with the cloud from R. Here are some links to a few:</p>
<ul>
<li><a href="https://r-spatial.org//r/2021/04/23/cloud-based-cubes.html">Cloud-based processing of satellite image collections with <code>rstac</code> and <code>gdalcubes</code></a></li>
<li><a href="https://csaybar.github.io/rgee-examples/">Run Google Earth Engine from R with <code>rgee</code></a></li>
<li><a href="https://kdvdecisions-blog.netlify.app/2020/04/18/obtaining-spatial-data-from-esri-rest-apis-in-r/">Obtain spatial data from ESRI REST APIs in R</a> or see package <a href="https://cran.r-project.org/web/packages/arcpullr/index.html"><code>arcpullr</code></a></li>
</ul>
<p>There are many more!!!</p>

</div>
</div>
            </section>

          </div>
        </div>
      </div>
<a href="rdemo.html" class="navigation navigation-prev " aria-label="Previous page"><i class="fa fa-angle-left"></i></a>
<a href="references.html" class="navigation navigation-next " aria-label="Next page"><i class="fa fa-angle-right"></i></a>
    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/clipboard.min.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-clipboard.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
  "sharing": {
    "github": false,
    "facebook": true,
    "twitter": true,
    "linkedin": false,
    "weibo": false,
    "instapaper": false,
    "vk": false,
    "whatsapp": false,
    "all": ["facebook", "twitter", "linkedin", "weibo", "instapaper"]
  },
  "fontsettings": {
    "theme": "white",
    "family": "sans",
    "size": 2
  },
  "edit": {
    "link": "https://github.com/jslingsby/spatial-r/edit/master/07-terra.Rmd",
    "text": "Edit"
  },
  "history": {
    "link": null,
    "text": null
  },
  "view": {
    "link": "https://github.com/jslingsby/spatial-r/blob/master/07-terra.Rmd",
    "text": null
  },
  "download": null,
  "search": {
    "engine": "fuse",
    "options": null
  },
  "toc": {
    "collapse": "subsection"
  }
});
});
</script>

</body>

</html>
